# Generated by Django 5.1.4 on 2025-01-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='adds_description',
            field=models.CharField(blank=True, default=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='adds_image',
            field=models.ImageField(blank=True, null=True, upload_to='adds/'),
        ),
        migrations.AddField(
            model_name='category',
            name='adds_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='adds_title',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
