# Generated by Django 5.1.4 on 2025-01-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_adds_description_category_adds_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='adds_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='adds_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
